import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import * as Docker from 'dockerode';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';

@Injectable()
export class ExecutionService {
  private readonly logger = new Logger(ExecutionService.name);
  private docker: Docker;

  constructor() {
    // Connect to local docker daemon
    this.docker = new Docker();
  }

  /**
   * Execute submitted files in an isolated Docker container.
   */
  async executeCode(files: { filename: string; content: string }[]): Promise<{ output: string; status: 'pass' | 'fail' }> {
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ai-fcp-exec-'));
    this.logger.log(`Created temp directory: ${tempDir}`);

    try {
      // 1. Write all files to the temporary directory
      for (const file of files) {
        const filePath = path.join(tempDir, file.filename);
        // Ensure subdirectories exist
        await fs.mkdir(path.dirname(filePath), { recursive: true });
        await fs.writeFile(filePath, file.content);
      }

      // 2. Create a generic evaluate.js to act as the entry point if it doesn't exist
      // In a real platform, this would be generated by AI specifically for testing
      const hasPackageJson = files.some(f => f.filename === 'package.json');
      let entryCommand = ['node', '-e', 'console.log("Code executed successfully! Tests passed.");'];

      if (hasPackageJson) {
        entryCommand = ['sh', '-c', 'npm install && npm test'];
      } else if (files.some(f => f.filename.endsWith('.ts') || f.filename.endsWith('.tsx'))) {
        // If TypeScript, use tsx/ts-node. For the sake of speed without installs, we'll try to run npx tsx.
        // Or just return a mock success for this sprint to validate Docker wiring.
        entryCommand = ['npx', '-y', 'tsx', files[0].filename];
      } else if (files.length > 0) {
        entryCommand = ['node', files[0].filename];
      }

      // 3. Spin up Docker container
      this.logger.log(`Starting container with command: ${entryCommand.join(' ')}`);
      
      const container = await this.docker.createContainer({
        Image: 'node:18-alpine',
        Cmd: entryCommand,
        HostConfig: {
          Binds: [`${tempDir}:/workspace`],
          Memory: 256 * 1024 * 1024, // 256 MB limit
          NetworkMode: 'none', // Disable network access for security
        },
        WorkingDir: '/workspace',
        Tty: false,
      });

      await container.start();

      // Wait for container to finish (with timeout)
      const stream = await container.logs({
        stdout: true,
        stderr: true,
        follow: true,
      });

      let output = '';
      stream.on('data', (chunk) => {
        // Remove Docker multiplexing headers (first 8 bytes)
        output += chunk.toString('utf-8').replace(/^[\x00-\x09\x0B-\x1F\x7F]+/, '');
      });

      // Simple 10 second timeout
      const result = await Promise.race([
        container.wait(),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Execution Timeout')), 10000))
      ]).catch(async (e) => {
        await container.kill().catch(() => {});
        throw e;
      });

      const statusCode = (result as any).StatusCode;
      
      // 4. Cleanup container
      await container.remove();

      return {
        output: output.trim() || 'No output generated.',
        status: statusCode === 0 ? 'pass' : 'fail',
      };

    } catch (error: any) {
      this.logger.error(`Execution failed: ${error.message}`);
      return {
        output: error.message || 'Execution failed due to an internal error.',
        status: 'fail',
      };
    } finally {
      // Cleanup temp directory
      await fs.rm(tempDir, { recursive: true, force: true }).catch(e => {
        this.logger.warn(`Failed to cleanup temp dir: ${tempDir}`);
      });
    }
  }
}
